# This rule is not used by the project node-operation-controller itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over nodeops.k8s.preferred.jp.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: node-operation-controller
    app.kubernetes.io/managed-by: kustomize
  name: nodeoperationtemplate-admin-role
rules:
- apiGroups:
  - nodeops.k8s.preferred.jp
  resources:
  - nodeoperationtemplates
  verbs:
  - '*'
- apiGroups:
  - nodeops.k8s.preferred.jp
  resources:
  - nodeoperationtemplates/status
  verbs:
  - get
