apiVersion: nodeops.k8s.preferred.jp/v1alpha1
kind: NodeOperationTemplate
metadata:
  labels:
    app.kubernetes.io/name: node-operation-controller
    app.kubernetes.io/managed-by: kustomize
  name: nodeoperationtemplate-sample
spec:
  template:
    metadata:
      labels:
        sample: ''
    spec:
      nodeName: node-operation-controller-worker
      jobSpec:
        template:
          spec:
            containers:
              - name: pi
                image: perl
                command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
            restartPolicy: Never
