apiVersion: nodeops.k8s.preferred.jp/v1alpha1
kind: NodeRemediationTemplate
metadata:
  labels:
    app.kubernetes.io/name: node-operation-controller
    app.kubernetes.io/managed-by: kustomize
  name: noderemediationtemplate-sample
spec:
  nodeSelector:
    'kubernetes.io/os': 'linux'
  template:
    nodeOperationTemplateName: 'example1'
    rule:
      conditions:
      - type: 'type1'
        status: 'status2'
