apiVersion: nodeops.k8s.preferred.jp/v1alpha1
kind: NodeDisruptionBudget
metadata:
  labels:
    app.kubernetes.io/name: node-operation-controller
    app.kubernetes.io/managed-by: kustomize
  name: nodedisruptionbudget-sample
spec:
  selector:
    kubernetes.io/hostname: node-operation-controller-worker
  maxUnavailable: 1
